import {NextRequest,NextResponse} from 'next/server';
import {getStore,updateStore} from '@/lib/store';
import {Card,emptyCard,questions,scoreCard,taskStatus,safeUrl,Application} from '@/lib/domain';
export const runtime='nodejs';
const fail=(message:string,status=400)=>NextResponse.json({error:message},{status});
export async function GET(req:NextRequest){const p=req.nextUrl.pathname;const db=await getStore();if(p==='/api/tasks')return NextResponse.json(db.tasks.sort((a,b)=>b.score-a.score));const match=p.match(/^\/api\/tasks\/([^/]+)(\/applications)?$/);if(match){const task=db.tasks.find(t=>t.id===match[1]);if(!task)return fail('Задача не найдена',404);return NextResponse.json(match[2]?db.applications.filter(a=>a.task_id===task.id):task);}return fail('Не найдено',404);}
export async function POST(req:NextRequest){try{const b=await req.json();const p=req.nextUrl.pathname;
 if(p==='/api/ai/clarify'){if(typeof b.draft_text!=='string'||b.draft_text.trim().length<20)return fail('Опишите задачу подробнее — минимум 20 символов.');return NextResponse.json({questions,mode:'demo'});}
 if(p==='/api/ai/build-card'){if(typeof b.draft!=='string'||!Array.isArray(b.answers)||b.answers.length!==3||b.answers.some((a:unknown)=>typeof a!=='string'||!a.trim()))return fail('Ответьте на все три вопроса.');return NextResponse.json({card_data:{...emptyCard,title:b.draft.slice(0,75),context:b.draft,criteria:b.answers[0],data:b.answers[1],constraints:b.answers[2]},mode:'demo'});}
 if(p==='/api/tasks'||p==='/api/tasks/score'){if(!b.card_data||Object.keys(emptyCard).some(k=>typeof b.card_data[k]!=='string'))return fail('Некорректная карточка.');const card=b.card_data as Card;if(card.links&&!safeUrl(card.links))return fail('Укажите ссылку HTTP или HTTPS.');const score=scoreCard(card);if(p.endsWith('/score'))return NextResponse.json({score});if(!card.title.trim()||!card.context.trim())return fail('Заполните название и контекст.');const task={id:crypto.randomUUID(),card_data:card,score,status:taskStatus(score),created_at:new Date().toISOString()};await updateStore(db=>db.tasks.push(task));return NextResponse.json(task,{status:201});}
 if(p==='/api/applications'){if(['task_id','team_name','idea','plan'].some(k=>typeof b[k]!=='string'||!b[k].trim()))return fail('Заполните все обязательные поля.');if(b.prototype&&(typeof b.prototype!=='string'||!safeUrl(b.prototype)))return fail('Укажите корректную ссылку на прототип.');const result=await updateStore(db=>{if(!db.tasks.some(t=>t.id===b.task_id))throw Error('Задача не найдена');if(db.applications.some(a=>a.task_id===b.task_id&&a.status==='ACCEPTED'))throw Error('Команда уже выбрана');const application:Application={id:crypto.randomUUID(),task_id:b.task_id,team_name:b.team_name.trim(),idea:b.idea.trim(),plan:b.plan.trim(),prototype:b.prototype||'',status:'PENDING'};db.applications.push(application);return application;});return NextResponse.json(result,{status:201});}return fail('Не найдено',404);
 }catch(e){return fail(e instanceof Error?e.message:'Не удалось обработать запрос');}}
export async function PATCH(req:NextRequest){try{const match=req.nextUrl.pathname.match(/^\/api\/applications\/([^/]+)\/status$/);if(!match)return fail('Не найдено',404);const {status}=await req.json();if(!['ACCEPTED','REJECTED'].includes(status))return fail('Некорректный статус');const app=await updateStore(db=>{const a=db.applications.find(a=>a.id===match[1]);if(!a)throw Error('Отклик не найден');if(db.applications.some(x=>x.task_id===a.task_id&&x.status==='ACCEPTED'))throw Error('Команда уже выбрана. Другие отклики заблокированы.');if(a.status!=='PENDING')throw Error('Отклик уже рассмотрен');a.status=status;return a;});return NextResponse.json({success:true,application:app});}catch(e){return fail(e instanceof Error?e.message:'Ошибка обновления',409);}}
