import {NextRequest,NextResponse} from 'next/server';
import {getStore,updateStore} from '@/lib/store';
import {Card,emptyCard,scoreCard,taskStatus,safeUrl,Application,BackendCard,fromBackendCard} from '@/lib/domain';
import {hashPassword,verifyPassword,setSession,clearSession,sessionUserId,validateSessionConfig} from '@/lib/auth';
export const runtime='nodejs';
const fail=(message:string,status=400)=>NextResponse.json({error:message},{status});
const publicTask=<T extends {owner_id?:string}>(task:T)=>task;
function taskWithState<T extends {id:string;owner_id?:string}>(task:T,apps:Application[]):T&{applications_open:boolean}{return {...task,applications_open:!!task.owner_id&&!apps.some(a=>a.task_id===task.id&&a.status==='ACCEPTED')};}
async function currentUser(req:NextRequest){const id=sessionUserId(req);return id?(await getStore()).users.find(u=>u.id===id)??null:null;}
async function aiRequest(path:string,body:unknown){const base=process.env.AI_BACKEND_URL??'http://127.0.0.1:8000';let url:URL;try{url=new URL(path,base);if(!['http:','https:'].includes(url.protocol))throw Error();}catch{return fail('Неверный адрес AI backend',500);}try{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(70000),cache:'no-store'});const data=await response.json();if(!response.ok)return fail(typeof data.detail==='string'?data.detail:'AI-сервис вернул ошибку',response.status);return NextResponse.json(data);}catch{return fail('AI-сервис недоступен',503);}}
export async function GET(req:NextRequest){const p=req.nextUrl.pathname;const db=await getStore();const user=await currentUser(req);if(p==='/api/auth/me')return NextResponse.json({user:user?{id:user.id,email:user.email}:null});if(p==='/api/tasks')return NextResponse.json(db.tasks.map(t=>publicTask(taskWithState(t,db.applications))).sort((a,b)=>b.score-a.score));if(p==='/api/my-tasks')return user?NextResponse.json(db.tasks.filter(t=>t.owner_id===user.id).map(t=>publicTask(taskWithState(t,db.applications)))):fail('Войдите в аккаунт',401);const match=p.match(/^\/api\/tasks\/([^/]+)(\/applications)?$/);if(match){const task=db.tasks.find(t=>t.id===match[1]);if(!task)return fail('Задача не найдена',404);if(match[2])return user&&task.owner_id===user.id?NextResponse.json(db.applications.filter(a=>a.task_id===task.id)):fail('Нет доступа к откликам',403);return NextResponse.json(publicTask(taskWithState(task,db.applications)));}return fail('Не найдено',404);}
export async function POST(req:NextRequest){try{const b=await req.json();const p=req.nextUrl.pathname;
 if(p==='/api/auth/register'){validateSessionConfig();const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||typeof b.password!=='string'||b.password.length<12)return fail('Укажите email и пароль не короче 12 символов');const user=await updateStore(db=>{if(db.users.some(u=>u.email===email))return null;const value={id:crypto.randomUUID(),email,password_hash:hashPassword(b.password)};db.users.push(value);return value;});if(!user)return fail('Пользователь уже существует',409);const result=NextResponse.json({user:{id:user.id,email:user.email}},{status:201});setSession(result,user.id);return result;}
 if(p==='/api/auth/login'){const email=typeof b.email==='string'?b.email.trim().toLowerCase():'';const user=(await getStore()).users.find(u=>u.email===email);if(!user||typeof b.password!=='string'||!verifyPassword(b.password,user.password_hash))return fail('Неверный email или пароль',401);const result=NextResponse.json({user:{id:user.id,email:user.email}});setSession(result,user.id);return result;}
 if(p==='/api/auth/logout'){const result=NextResponse.json({success:true});clearSession(result);return result;}
 if(p==='/api/ai/clarify'){if(typeof b.draft_text!=='string'||b.draft_text.trim().length<20)return fail('Опишите задачу подробнее — минимум 20 символов.');return aiRequest('/api/ai/clarify',{draft_text:b.draft_text});}
 if(p==='/api/ai/build-card'){if(typeof b.draft_text!=='string'||!Array.isArray(b.qa_pairs)||b.qa_pairs.length!==3||b.qa_pairs.some((a:unknown)=>!a||typeof a!=='object'||typeof (a as {question?:unknown}).question!=='string'||typeof (a as {answer?:unknown}).answer!=='string'))return fail('Ответьте на все три вопроса.');const result=await aiRequest('/api/ai/build-card',{draft_text:b.draft_text,qa_pairs:b.qa_pairs});if(!result.ok)return result;const data=await result.json() as {card:BackendCard;scoring:unknown};return NextResponse.json({card_data:fromBackendCard(data.card),scoring:data.scoring});}
 if(p==='/api/tasks'||p==='/api/tasks/score'){if(!b.card_data||Object.keys(emptyCard).some(k=>typeof b.card_data[k]!=='string'))return fail('Некорректная карточка.');const card=b.card_data as Card;if(card.links&&!safeUrl(card.links))return fail('Укажите ссылку HTTP или HTTPS.');const score=scoreCard(card);if(p.endsWith('/score'))return NextResponse.json({score,status:taskStatus(score)});const user=await currentUser(req);if(!user)return fail('Войдите в аккаунт',401);if(!card.title.trim()||!card.context.trim())return fail('Заполните название и контекст.');const task={id:crypto.randomUUID(),owner_id:user.id,card_data:card,score,status:taskStatus(score),created_at:new Date().toISOString()};await updateStore(db=>db.tasks.push(task));return NextResponse.json(publicTask(taskWithState(task,[])),{status:201});}
 if(p==='/api/applications'){const user=await currentUser(req);if(!user)return fail('Войдите в аккаунт',401);if(['task_id','team_name','idea','plan'].some(k=>typeof b[k]!=='string'||!b[k].trim()))return fail('Заполните все обязательные поля.');if(b.prototype&&(typeof b.prototype!=='string'||!safeUrl(b.prototype)))return fail('Укажите корректную ссылку на прототип.');const result=await updateStore(db=>{const task=db.tasks.find(t=>t.id===b.task_id);if(!task)throw Error('Задача не найдена');if(!task.owner_id)throw Error('Это демонстрационная задача, приём откликов закрыт');if(task.owner_id===user.id)throw Error('Нельзя откликнуться на свою задачу');if(db.applications.some(a=>a.task_id===b.task_id&&a.status==='ACCEPTED'))throw Error('Команда уже выбрана');const application:Application={id:crypto.randomUUID(),task_id:b.task_id,team_name:b.team_name.trim(),idea:b.idea.trim(),plan:b.plan.trim(),prototype:b.prototype||'',status:'PENDING'};db.applications.push(application);return application;});return NextResponse.json(result,{status:201});}return fail('Не найдено',404);
 }catch(e){return fail(e instanceof Error?e.message:'Не удалось обработать запрос');}}
export async function PATCH(req:NextRequest){try{const match=req.nextUrl.pathname.match(/^\/api\/applications\/([^/]+)\/status$/);if(!match)return fail('Не найдено',404);const user=await currentUser(req);if(!user)return fail('Войдите в аккаунт',401);const {status}=await req.json();if(!['ACCEPTED','REJECTED'].includes(status))return fail('Некорректный статус');const app=await updateStore(db=>{const a=db.applications.find(a=>a.id===match[1]);if(!a)throw Error('Отклик не найден');const task=db.tasks.find(t=>t.id===a.task_id);if(task?.owner_id!==user.id)throw Error('Нет доступа к задаче');if(db.applications.some(x=>x.task_id===a.task_id&&x.status==='ACCEPTED'))throw Error('Команда уже выбрана. Другие отклики заблокированы.');if(a.status!=='PENDING')throw Error('Отклик уже рассмотрен');a.status=status;return a;});return NextResponse.json({success:true,application:app});}catch(e){return fail(e instanceof Error?e.message:'Ошибка обновления',409);}}
